### ISSUE TITLE
Visual Line Mode no longer scrolls

### ISSUE THREAD

**Issue by rudedogg** [XVimProject/XVim2#140]
Using Xcode Version 9.3 (9E145)

I noticed when using visual line mode (`V`) + scrolling (`j`/`h`) the code editor no longer scrolls down/up. This seems to affect other movement commands (`V`+`}`, `V`+`{`, `V`+`pgDN`, `V`+`pgUP`).

I **think** this used to work in Xcode 9.2.

**Comment by jberglinds** [comment]
I just noticed the same thing. 
It definitely worked on 9.2.

**Comment by pebble8888** [comment]
I fixed in develop branch.
Please check.

**Comment by rudedogg** [comment]
@pebble8888 Thanks! I tried it out and everything seems to work except for `V+pgDn/V+pgUp`

 I'm totally fine with this, I usually just use `j/h` in visual line mode. Just wanted to report for others.

**Comment by pebble8888** [comment]
fixed in master branch.
won't fix about V+pgDN, V+pgUP

**Comment by ooopscc** [comment]
Latest develop or master, this issue persists when scroll exceeds one screen.
![1](https://user-images.githubusercontent.com/1056803/49150186-11b37000-f347-11e8-8ab9-33ae31994383.gif)

**Comment by pebble8888** [comment]
@ooopscc 
Please write xcode version and macOS version.

**Comment by rudedogg** [comment]
@pebble8888 I have this issue too. Xcode 10.1 and macOS 10.14.1

There seems to be a sort of threshold where it works correctly, but once the selection goes too far it stops scrolling. Wanted to mention that so if it appears to work at first.

**Comment by ooopscc** [comment]
Xcode 10.1 and macOS 10.14.1.

**Comment by ooopscc** [comment]
Confirmed. Thanks.
