### ISSUE TITLE
support ARM mac

### ISSUE THREAD

**Issue by pebble8888** [XVimProject/XVim2#303]
XVim2 has Intel assemby code.

**Comment by sobri909** [comment]
I'm about 30 years out of date on ARM assembly 😂 The last time I worked with it was on Acorn. But I'd be happy to contribute towards an Apple Transition Developer Kit!

**Comment by rudedogg** [comment]
Is this the assembly?

https://github.com/XVimProject/XVim2/blob/5b1033b4ee9db5c4821f31d9f8f2688247e47db6/XVim2/Xcode/SourceEditorViewWrapper.s

**Comment by pebble8888** [comment]
@rudedogg Yes.

**Comment by jspavlick** [comment]
Is this still a problem? A friend of mine with one of the developer preview Mac mini's was able to run make and it compiled successfully. However he didn't code sign Xcode so he can't confirm fully if XVim2 runs or not.

**Comment by jrsharp** [comment]
Yes, this still appears to be an issue.  I was able to build XVim2 successfully for Xcode 12.2, but Xcode does not seem to like installing/running Xcode plugins compiled for x86-64 only (using Rosetta2), as XVim2 currently excludes arm64.  Initial attempt to build for arm64 failed -- will have to dig into it further.

**Comment by jspavlick** [comment]
Is there anyway I can help (maybe by trying to cross-compile)? I have an Intel based MBP running 10.15.7 Catalina.

**Comment by jrsharp** [comment]
Well, the issue seems to be well understood, as identified above -- replacing the x86 asm in SourceEditorViewWrapper.s.  In the short term, Xcode can be forced to be opened using Rosetta2, and I can confirm XVim2 functions when using Rosetta2.

**Comment by jspavlick** [comment]
Yeah, I saw the x86 assembly. But I was wondering maybe there is/are other problems in addition to that.

That's good news in terms of a (temporary) workaround. That's enough for me to order an M1 machine.

**Comment by RookieZn** [comment]
> Yeah, I saw the x86 assembly. But I was wondering maybe there is/are other problems in addition to that.
> 
> That's good news in terms of a (temporary) workaround. That's enough for me to order an M1 machine.

@jspavlick What's the workaround to use XVim2 on ARM mac? Thanks.

**Comment by jspavlick** [comment]
@RookieZn I don't know. I don't have my M1 mac yet. As jrsharp eluded do, if you force Xcode to run using Rosetta2 (it's a universal binary, right? So it will run the x86 version through emulation) then it will work, but presumably everything (compiling etc) will be slower?

**Comment by unchartedworks** [comment]
There is a workaround. You can run Xcode using rosetta. Xcode is an universal application.
0. Close Xcode
1. Go to Applications and right click Xcode.
2. Click "Get info" menu item in Context menu.
3. Tick "Open using rosetta"
4. Run Xcode
Please notes that please make sure you have installed Xvim2.

**Comment by r-plus** [comment]
hmm, its assemby code is for call swift only interface (have not @obj attribute) instance method from xvim(objc), right?

**Comment by unchartedworks** [comment]
It's possible to convert Intel assembly to Objective-C/C using decompiler. [https://www.hopperapp.com/](url)

**Comment by r-plus** [comment]
I found one more issue dependent intel arch.

XVim2 project imported `rd_route` project https://github.com/rodionovd/rd_route for getting swift function (property/method) pointer that not supporting arm arch.
We must fix it or change the dependent source/project for it.

NOTE: yes, using function `function_ptr_from_name` from it is for invoke swift method.
It is same purpose of `SourceEditorViewWrapper.s` assemble code.

**Comment by iT-Boyer** [comment]
> There is a workaround. You can run Xcode using rosetta. Xcode is an universal application.
> 
> 1. Close Xcode
> 2. Go to Applications and right click Xcode.
> 3. Click "Get info" menu item in Context menu.
> 4. Tick "Open using rosetta"
> 5. Run Xcode
>    Please notes that please make sure you have installed Xvim2.
> 
> It's unfortunately that the performance of Xcode is worse using Rosetta, especially building a big project.

I do this five steps and run XCode ，see Edit->Xvim2 -> about：
```
-------- Debug Info -------
XVim2 revision : 540f9b8cdbbc2a440cfd91f551981e801fc08f17
OS Version : Version 11.1 (Build 20C69)
Xcode Version : 12.3

--- .xvimrc ---
N/A
--------------
```
but , xvim2 not work in code editer .

**Comment by unchartedworks** [comment]
> > There is a workaround. You can run Xcode using rosetta. Xcode is an universal application.
> > 
> > 1. Close Xcode
> > 2. Go to Applications and right click Xcode.
> > 3. Click "Get info" menu item in Context menu.
> > 4. Tick "Open using rosetta"
> > 5. Run Xcode
> >    Please notes that please make sure you have installed Xvim2.
> > 
> > It's unfortunately that the performance of Xcode is worse using Rosetta, especially building a big project.
> 
> I do this five steps and run XCode ，see Edit->Xvim2 -> about：
> 
> ```
> -------- Debug Info -------
> XVim2 revision : 540f9b8cdbbc2a440cfd91f551981e801fc08f17
> OS Version : Version 11.1 (Build 20C69)
> Xcode Version : 12.3
> 
> --- .xvimrc ---
> N/A
> --------------
> ```
> 
> but , xvim2 not work in code editer .

I have tested it on Xcode 12.2, it works. Because Xcode 12.3 isn't usable on my Mac, I haven't tested it on Xcode 12.3.

**Comment by r-plus** [comment]
Do you add Xcode 12.3 UUID?

**Comment by iT-Boyer** [comment]
YES，i set UUID by this command：
```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
```
 Now , when the mouse is focused on the editor, Xcode cannot respond for a long time.

**Comment by smolck** [comment]
Hello! So, my understanding from reading through this issue is that in order for XVim to work natively on M1, [this assembly code](https://github.com/XVimProject/XVim2/blob/5b1033b4ee9db5c4821f31d9f8f2688247e47db6/XVim2/Xcode/SourceEditorViewWrapper.s) needs to be removed/changed to work on ARM somehow, and `rd_route` also needs to be swapped out for something else or removed. Is that correct?

If so, I have a few questions; for starters, what does that x86 assembly do exactly/why is it used? Could it be replaced by Objective-C or C code?

Also, a quick glance over [`rd_route`](https://github.com/rodionovd/rd_route)'s README seems to suggest that it isn't very safe to use; I presume it can be used safely, but regardless I guess it could/should be replaced for something else? Perhaps a refactor could render it unnecessary?

I'm happy to help with this where I can, even if that just means testing out a PR or PRs on my machine to verify it works on M1.

Also, I can confirm that running Xcode under Rosetta does allow XVim to work, but I suspect running Xcode under Rosetta is something many M1 users (myself included) would rather avoid, considering the advantages to running Xcode natively on the M1.

**Comment by jspavlick** [comment]
@smolck I believe your assessment is correct. 

I do not know what the x86 assembly is doing. I am by no means an assembly expert. However, @r-plus is seeming to indicate that the assembly code is doing the same thing as rd_route, or somehow calling it? That doesn't seem to be the case to me, but I am no expert. 

XVim2 is only using `function_ptr_from_name` from `rd_route`. If you read around in `rd_route.c` you can kind of get an idea of what it's doing. If you read around in `SourceEditorViewWrapper.swift` you can kind of get an idea on how it's being used. 

I predict that converting the x86 assembly to ARM will be easier than porting the functionality of `function_ptr_to_name` but I don't know. (Unless r-plus is correct [as is my understanding of his earlier comment] and they're doing the same thing?)

My M1 Mac is on the way, and when it gets here I'll be happy to play with `function_ptr_to_name` as well as help in any other way I can. 

In the meanwhile, I have posted a $500 bug bounty on this for anyone who is more competent than I am.

**Comment by smolck** [comment]
> XVim2 is only using function_ptr_from_name from rd_route. If you read around in rd_route.c you can kind of get an idea of what it's doing. If you read around in SourceEditorViewWrapper.swift and SourceEditorDataSourceWrapper.swiift you can kind of get an idea on how it's being used.

Just looking at that first file, this is where `function_ptr_from_name` is used:
https://github.com/XVimProject/XVim2/blob/b723d4e91a973a4c83f908198091725abaf449c3/XVim2/Xcode/SourceEditorViewWrapper.swift#L102-L106

Those seem to just be pointers to Objective-C functions, right? For example, `fpSetCursorStyle` appears to reference [this Objective-C function](https://github.com/XVimProject/XVim2/blob/b723d4e91a973a4c83f908198091725abaf449c3/XVim2/Xcode/SourceEditorViewProxy.m#L118) (or a similar one somewhere else in the code). In that case couldn't either (a) some sort of interop be done between Swift & Objective-C to remove the need for `function_ptr_from_name` (asking because I'm not super familiar with Swift or Objective-C), or (b) `SourceEditorViewWrapper.swift` just be rewritten in Objective-C so no interop is necessary?

As for (b), I imagine that might be the easier way of doing this, unless there's a serious reason why `SourceEditorViewWrapper` was written in Swift instead of Objective-C, or unless that class/file has to be written in Swift for some reason.

Again, though, I'm not familiar with this codebase (and hardly know anything about Swift/Objective-C), so I might be wrong here. (And even if I'm not and those are valid solutions, I don't think I currently have the understanding/knowledge necessary to implement the fix.)

**Comment by r-plus** [comment]
Sorry for confusion. 

Both parts (assembly code and rd_route) is necessary for invoke Swift method implemented in Xcode.app by Apple.

1. getting Swift function (method) pointer by function_ptr_from_name
2. Then call that pointer with argument by XVim assembly code 

NOTE: Usually, pure Swift function (not have objc interface) have not dynamic callable system out side of original module (in this case, Xcode).

**Comment by jspavlick** [comment]
Yeah, after studying the code a little more, I think @r-plus is completely correct.

Let me explain what I think is going on @smolck. `SourceEditorViewWrapper` wraps a `SourceEditorView` which is from some Apple internal framework. It is a **Swift** subclass of `NSView`. It's mangled name is `_TtC15IDESourceEditor19IDESourceEditorView`. It has methods on it like `SourceEditor.SourceEditorView.setSelectedRange(_: SourceEditor.SourceEditorRange, modifiers: SourceEditor.SourceEditorSelectionModifiers) -> ()`

`SourceEditorViewWrapper` wants to invoke these methods. When everything was Objective-C, you could just do something like `[object performSelector:NSSelectorFromString(@"_someCrazyPrivateMethod")];` but in Swift land (unless the method is annotated with @objc) you cannot do this. 

The workaround (which seems to be quite brilliant) is to get a function pointer that points to the function/method in question (I guess it's sitting in a v-table somewhere?) and then "manually" invoke  the function as a method, by remembering to pass `self` as an argument. This manual invocation is what the x86 assembly code does *I THINK*.

**Comment by jspavlick** [comment]
@smolck could you please save this file as `main.c` and then run `gcc main.c && ./a.out` on your M1 mac and tell us what happens? https://pastebin.com/vKc8RG2K I stripped everything out of rd_route.c except `function_ptr_from_name` let's see if it works without any modification. It works on my Intel machine, for whatever little it's worth. 😅

**Comment by qiudaomao** [comment]
@jspavlick
You are right, the magic SourceEditorViewWrapper.s does is to implement the swift function call ABI.
1. Save registers
2. Place all arguments in the right registers or stack
3. call the function by symbol address
4. restore the saved registers
5. return

Need rewrite the whole procedure by ARM, de-compile some swift arm binaries should helping known how swift call a symbol in ARM.

**Comment by jspavlick** [comment]
> @jspavlick
> 
> You are right, the magic SourceEditorViewWrapper.s does is to implement the swift function call ABI.
> 
> 1. Save registers
> 
> 2. Place all arguments in the right registers or stack
> 
> 3. call the function by symbol address
> 
> 4. restore the saved registers
> 
> 5. return
> 
> 
> 
> Need rewrite the whole procedure by ARM, de-compile some swift arm binaries should helping known how swift call a symbol in ARM.

And I think that's totally doable. But what do you think the chances are we get function_ptr_from_name also working on ARM?

**Comment by r-plus** [comment]
@jspavlick yes, completely correct.

I’m thinking fishhook https://github.com/facebook/fishhook implementation is maybe helpful for getting function pointer on ARM. (looks like not have function like rd_route, so need work to fit for XVim)

**Comment by smolck** [comment]
@jspavlick Thank you for the detailed explanation, that helps a lot!

> @smolck could you please save this file as main.c and then run gcc main.c && ./a.out on your M1 mac and tell us what happens? https://pastebin.com/vKc8RG2K I stripped everything out of rd_route.c except function_ptr_from_name let's see if it works without any modification. It works on my Intel machine, for whatever little it's worth. 😅

Just a note, I had to remove the `#include "rd_route.h"` at the top in order for it to compile, since I don't have that file (nor in this case do I really need it). After doing that slight modification, I get this output when I compile and run the code:
```
main.c:125:
	error: The given Mach-O image header is missing some important sections.
zsh: segmentation fault  ./a.out
```
Also, another note, this runs fine under Rosetta. That's probably insignificant, but figure I'll put it here anyways. In addition, I can perhaps get a more detailed stacktrace with `gdb` if necessary.

However, in `rd_route`'s README the library [`libevil`](https://github.com/landonf/libevil_patch) is suggested for iOS (and thus I'm guessing it would also work on the M1), and it seems to have the API necessary (without any extra modification) to do the same as what `function_ptr_from_name` does. So maybe we can use that instead of `rd_route`, and maybe it's a better alternative than `fishhook`, @r-plus?

> You are right, the magic SourceEditorViewWrapper.s does is to implement the swift function call ABI.
> 
>     1. Save registers
> 
>     2. Place all arguments in the right registers or stack
> 
>     3. call the function by symbol address
> 
>     4. restore the saved registers
> 
>     5. return
> 
> 
> Need rewrite the whole procedure by ARM, de-compile some swift arm binaries should helping known how swift call a symbol in ARM.

Where is this assembly called in the codebase? I'm guessing once the ARM assembly is written all that will be needed is to add code to use the ARM assembly wherever the x86 assembly is called currently if the code is running on an Apple Silicon machine?

**Comment by r-plus** [comment]
@smolck if it works, best alternative than fishhook :) 
Previously I found this issue https://github.com/landonf/libevil_patch/issues/1 in libevil, so maybe libevil is not compatible for arm64 (not tested)

> Where is this assembly called in the codebase?

These lines define the function names implemented by assembly.
https://github.com/XVimProject/XVim2/blob/master/XVim2/Xcode/SourceEditorViewWrapper.s#L30-L48

These lines are declaration of functions to use that function in this file like header file in C/C++/ObjC.
Assembly implemented function will be called when invoke that function.
For example, invoke `func _get_cursor_style(_: UnsafeRawPointer)` function from SourceEditorViewWrapper.swift, `scev_wrapper_call` function will be called.
https://github.com/XVimProject/XVim2/blob/master/XVim2/Xcode/SourceEditorViewWrapper.swift#L58-L63

When we add support ARM, we should add `#if` preprocessor to select which code will be used.

**Comment by smolck** [comment]
@r-plus Thank you for the info! With that, after the x86 assembly is converted to ARM assembly, then the conditional use/preprocessor part should be fairly simple/straightforward.

Speaking of the x86 assembly to ARM assembly conversion, I just found this repository that might be helpful for the task: 
https://github.com/below/HelloSilicon

**Comment by smolck** [comment]
One thing I am curious about is if there really isn't an alternative to all of this in order to call the `SourceEditorView` methods? Having to dive into assembly and C in order to invoke some methods that should probably be exposed through a Swift/Objective-C interface just feels wrong to me. Is there really not another way of achieving what the current code does _without_ the C and assembly code?

**Comment by jspavlick** [comment]
What about something like this, @smolck ?

Check out this snippet: Imagine that "A" is Apple's `SourceEditorView`. (actually in objc it's `_TtC15IDESourceEditor19IDESourceEditorView`) Since it is a subclass of `NSView`, this should work. We can get in-between "foo" which is a swift method (not objc) this way, but we have no way of calling super...I think? 

But if "foo" is private, this doesn't work. I think due to the fact that it's statically dispatched. 

In C/Obj-C we were able to "expose" private methods/functions by declaring them in a .h file, and then basically "promise" that they will be there at link-time/runtime. I don't know if that is possible with Swift, or if the tooling exists yet(?)

```
import UIKit

private class A: UIViewController {
  func foo() {
    print("A")
  }
}

private class B: A {
  override func foo() {
    print("B")
  }
}

@main
class AppDelegate: UIResponder, UIApplicationDelegate {

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    // Override point for customization after application launch.
    let a = A()
    a.foo()
    object_setClass(a, B.self)
    a.foo()
    return true
  }

}
```

**Comment by smolck** [comment]
@jspavlick Hmm, I see. Perhaps [this library](https://github.com/mhdhejazi/Dynamic) could help/work? I tried modifying the code to use that myself but I keep getting an error about "no suitable image found" when trying to debug XVim from Xcode.

Also, is there really no alternative API then to `SourceEditorView` that provides the same functionality (with `setCursorStyle` and the like)? I would _think_ that there would be, but I'm not familiar with the ecosystem so I don't know. Maybe there wasn't when this solution was originally done, but there is now (that assembly code hasn't been touched in 2 years)?

Looking at some x86 assembly vs. the ARM assembly equivalent, it shouldn't be too hard to port the existing code to run on ARM (at least for someone who actually knows Assembly, unlike myself 😅), so no Swift/Objective-C alternative isn't necessarily a blocker. However, I can't help but wonder if there's a better way of doing this that doesn't require such low-level code, and that's more straightforward.

**Comment by jspavlick** [comment]
I don't think that library will work. It seems made for working with Obj-C classes. We are working with a Swift class (but a subclass of an Obj-C class). 

I have no idea. I thought that Xcode was using a SourceEditorView internally, and XVim2 has to "talk to it" somehow. We can't really change what Xcode is doing internally. 

I'm with you. It would be great if we could find the original authors of the code to chime in. Maybe they gave up programming for greener pastures. 😅

**Comment by 215eight** [comment]
@JugglerShu by any chance would you be able to provide some input on this? Thank you in advance!

**Comment by JugglerShu** [comment]
@215eight  I'm surprised someone here still calls my name, hah. Unfortunately I have been away from this project for a while and I don't have much information about the assembly code. I remember that such assembly code was introduced to call some Xcode swift functions (as discussed in this thread.)
This is my guess but I think there are no other good way to call the SourceEditorView methods without such assembly at the moment.
Let me check the code and I'll post anything I find.

**Comment by r-plus** [comment]
In my short research, all of the case getting function pointer address by rd_route are got address by `NSLookupSymbolInImage`.

It works fine on my M1 mac, we clear the problem about getting function pointer in ARM.
Last issue is assembly code.

**Comment by jspavlick** [comment]
@r-plus that's great news. That's not what we seemed to find earlier with my little rd_route.c file. https://github.com/XVimProject/XVim2/issues/303#issuecomment-752348346

But maybe for swift functions/methods it works!?

My M1 Mac is still in the mail. (I'm currently living in a country where it takes some time for packages to arrive from the US) So I am not able to help very much until it arrives. My plan though, for helping with assembly code conversion is this:

Create a simple file that emulates SourceEditorView (a swift subclass of NSView) and invoke a swift method. Something like this: https://pastebin.com/td9xuiNF

Then run `swiftc` to compile the code into an executable. Then, disassemble the executable and try to figure out how invoke a swift method works. I don't know how to disassemble an executable off the top of my head, but I know it's possible. 

What do you think?

**Comment by r-plus** [comment]
@jspavlick your modified rd_route.c is almost correct without line:150
symbol name is `_print_stuff` is correct in this case.

```
~/gitclone/XVim2 arm64 (arm_test)$ tail test.c
void print_stuff() {
  printf("stuff!\n");
}

int main() {
  void (*print_stuff_ptr)(void) = function_ptr_from_name("_print_stuff", NULL);
  (*print_stuff_ptr)();
  return 0;
}

~/gitclone/XVim2 arm64 (arm_test)$ clang test.c
~/gitclone/XVim2 arm64 (arm_test)$ ./a.out
stuff!
```

**Comment by jspavlick** [comment]
oooooo. OK, great! (I wonder why it works as-is on my Intel MBP. Oh well) 

Yes Hopper does look complex. Maybe there is a simpler, command line tool? Maybe we can disassemble an Intel binary and try to match it to the existing SourceViewWrapper.s code?

**Comment by r-plus** [comment]
I found swiftc have the ability to output assembly code `-emit-assembly` option.

**Comment by smolck** [comment]
> Create a simple file that emulates SourceEditorView (a swift subclass of NSView) and invoke a swift method. Something like this: https://pastebin.com/td9xuiNF

> I found swiftc have the ability to output assembly code -emit-assembly option.

Using the code from the pastebin above and the `-emit-assembly` option to compile it, here's the result: https://gist.github.com/smolck/142431e0122633e70d21d211a5bf5a6c

**Comment by r-plus** [comment]
maybe this document is helpful to writing 64bit assembly for swift
https://github.com/apple/swift/blob/main/docs/ABI/RegisterUsage.md

**Comment by jspavlick** [comment]
> > Create a simple file that emulates SourceEditorView (a swift subclass of NSView) and invoke a swift method. Something like this: https://pastebin.com/td9xuiNF
> 
> > I found swiftc have the ability to output assembly code -emit-assembly option.
> 
> Using the code from the pastebin above and the `-emit-assembly` option to compile it, here's the result: https://gist.github.com/smolck/142431e0122633e70d21d211a5bf5a6c

My x86 gist is just as terrifying 😆  https://gist.github.com/jspavlick/392b7689647af540f5a8227c8dab3db8

**Comment by smolck** [comment]
@jspavlick Haha, it is indeed. I think though that given those two sets of code, plus the changes r-plus made, I _might_ be able to come up with something that works. No guarantees though, unfortunately.

**Comment by smolck** [comment]
Hmm, so the initial problem I'm running into/will run into is that I don't know the equivalent to things like this in ARM assembly:

```assembly
pushq %rbp
movq  %rsp, %rbp

# ...

movq    %rbx, (%rsp)
movq    %r12, 8(%rsp)
movq    %r13, 16(%rsp)
movq    %r14, 24(%rsp)
movq    %r15, 32(%rsp)
```

What I mean is not so much the normal function and register equivalents, but rather the equivalent to `%rsp` and perhaps `%rbp`? I looked around maybe a week or two ago but couldn't really seem to find anything about the equivalent to that register in ARM assembly. Any ideas? It isn't mentioned in that doc @r-plus linked (which is really useful btw!).

Reading from [this SO answer](https://stackoverflow.com/a/51347294), `%rsp` appears to be a register for stack operations, but even after seeing the equivalent ARM assembly to x86 I'm not sure of the equivalent expressions to the code above. (Note this is also probably due to my not really understanding what the functions `movq` and such do/how they are used, but that information should be easy to learn/find. At least I hope so 😅)

**Comment by JugglerShu** [comment]
@smolck I haven’t followed the thread but rsp is a stack pointer. In ARM it should be SP register.
I think the code you wrote above is at the beginning of a function.
 - saving stack frame (rsp rbp operation)
 - Saving r12-15 registers in stack
 
 I think this is usual x64 calling convention. So when converted you can use equivalent ARM calling convention.

**Comment by jspavlick** [comment]
ok so I just spent some time looking over the x86 assembly code and I've come to a much better, however incomplete, understanding. This little page is helpful. https://wiki.cdot.senecacollege.ca/wiki/X86_64_Register_and_Instruction_Quick_Start

Basically the Intel CPU in all of our Intel machines has a bunch of registers. SourceEditorViewWrapper.s basically stores the value of every register on the stack (pushing the values on). Go look at that `leaq -240(%rsp) %rsp` that's kind of like calling `malloc(240)` if you want to think of it that way, then `movq` every register value onto the stack. Then it sets up `self` (using `%r13` and the function pointer (i.e. the method that we are invoking) then `callq` to basically jump there. (You see similar code, using %r13 and callq in my x86 gist, go check out _main) 

Then upon returning, it pops every value off of the stack in reverse, re-loading up the registers.

**Comment by smolck** [comment]
Okay, thanks to that info, now I'm starting to understand what's going on better! So, if I understand correctly, then the main part of `SourceEditorViewWrapper.s` is this:
```assembly
# Body
    movq  (%rdi), %r13 # Load the target 'self'

    pushq  $0 # Keep 16-byte SP alignment
    pushq  8(%rdi)  # Push the target function

# Shuffle up arguments
    movq  %rsi, %rdi
    movq  %rdx, %rsi
    movq  %rcx, %rdx
    movq  %r8, %rcx
    movq  %r9, %r8

# CALL
    callq *(%rsp)

    addq $16, %rsp
```
And everything else is cleanup/putting things back where they belong (i.e. to the proper registers)?

One thing I'm still unsure about is what is meant by the comments `Shuffled args` and `Shuffle up arguments` in `SourceEditorViewWrapper.s`/what that's doing?

**Comment by jspavlick** [comment]
Yes, I believe your assessment is correct. I'm trying to understand the `shuffle` stuff too, and I can't. Take a look at ```    // RAX, RDX Used for return values
    // RCX Used for return values
    // R8 Used for return values``` I don't know where this knowledge comes from, but we'll have to find the equivalent knowledge for arm64.

Who wrote is the magical wizard who wrote this file, originally? I see it was renamed?

**Comment by JugglerShu** [comment]
I believe it’s x64 calling conversation to swift calling conversation conversion.
It seems swift uses r13 as self.
https://github.com/eaplatanios/swift-language/blob/master/docs/ABI/RegisterUsage.md

Shuffling part is not actually shuffling args but just sliding position by one.

**Comment by smolck** [comment]
> but we'll have to find the equivalent knowledge for arm64.

That's the problem I'm having right now; for some reason there appears to be very little documentation on x64 assembly vs arm assembly, and it's quite frustrating.

However, I did find this write up which seems pretty useful: https://developer.apple.com/documentation/xcode/writing_armv6_code_for_ios

At the bottom of that there's a section regarding the prolog/epilog of a function, and some code as an example. My understanding from looking over the code there/reading a bit (I think I'll properly read through the whole thing later) is that the equivalent to `leaq -240(%rsp), %rsp` would be `sub sp, sp, #240`, but I'm not sure if that's correct. But perhaps specifically this code from that document might be useful:

```assembly
push   {r4-r7, lr}     // Save Lr, R7, R4-R6.
mov    r6, r11         // Move high registers to low registers, so
mov    r5, r10         //  they can be saved. (Skip this part if
mov    r4, r8          //  the routine doesn’t use R8, R10, or R11.)
push   {r4-r6)         // Save R8, R10, R11 (now in R4-R6).
add    r7, sp, #24     // Adjust R7 to point to saved R7.
sub    sp, #36         // Allocate space for local storage.
```

If nothing else, it seems like a useful example of arm assembly.

**Comment by r-plus** [comment]
I've been learning x64 assembly for the last few days before learning arm64 assembly.
Now I totally understood current assembly code what to do.

made this pull request for adding many comment and refactoring. https://github.com/XVimProject/XVim2/pull/352

**Comment by r-plus** [comment]
Hey guys!
I'm glad to announce start point to support arm64 architecture!

This is the branch to building universal binary. (Thank you @JugglerShu for commit permission)
It works basically operation in my test.
https://github.com/XVimProject/XVim2/tree/feature/support_arm

Let me know to this issue if you have the problem in arm, but not problem in intel.

## known issues for arm
- Xcode will crash when type `Ctrl+v` to enter Visual Block mode then type `j` key. I'm not sure how to resolve this.

**Comment by jspavlick** [comment]
OMG!

**Comment by r-plus** [comment]
ah, first known issue I wrote is only for Debug build.
uum, that's curious... but okey, mark as resolved.

**Comment by r-plus** [comment]
Wow, I found test case for XVim inside edit menu.

This is result on ARM.
<img width="917" alt="スクリーンショット 2021-01-15 21 43 38" src="https://user-images.githubusercontent.com/425216/104728858-e1272e00-577a-11eb-958c-70fed83e47c1.png">

and intel (Rosetta) result
<img width="966" alt="intel_rosetta" src="https://user-images.githubusercontent.com/425216/104732039-f2bf0480-577f-11eb-8ab5-22a27e0d25cb.png">

Same result.
Hmm, is it release able quality...?

**Comment by jspavlick** [comment]
Are these issues present on Intel? I can't seem to find how to run these tests in Edit.

**Comment by r-plus** [comment]
not yet checked about it.

tests are here.
Edit menu (in menu bar) -> XVim -> Test categories -> All

**Comment by jspavlick** [comment]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/5431318/104735128-474b8b00-5752-11eb-80fd-7cae13800c6b.png">
Am I crazy? I'm on master b723d4e91a973a4c83f908198091725abaf449c3

**Comment by r-plus** [comment]
Oh, its menu will show only in debug mode. debug mode will add file logging AFAIK.
please did this.

```
echo "set debug" >> ~/.xvimrc
```

**Comment by jspavlick** [comment]
Got it!

Oh wow, Intel performs terribly! Can someone else with an Intel machine confirm this? This seems insane? 

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/5431318/104743521-d78ecd80-575c-11eb-9a01-1191ca5bdab8.png">

I ran it a second time and got this:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/5431318/104743781-1e7cc300-575d-11eb-83f4-6edb1c3b0942.png">

**Comment by r-plus** [comment]
In my intel mac (MBP Late 2016), same three failure result I previously pasted.

**Comment by jspavlick** [comment]
Why does mine fail so badly? Maybe we can ignore it?

**Comment by smolck** [comment]
@jspavlick Is there anything other than `set debug` in you `.xvimrc`?

For me, I ran the tests on the latest from the `feature/support_arm` branch, and this was the result:
![Screen Shot 2021-01-15 at 11 15 02 AM](https://user-images.githubusercontent.com/46855713/104758193-ad6ce980-5723-11eb-9acd-7dc3eb0791a6.png)

Running it under Rosetta appeared to gave the same result.

Just from a quick test moving around the editor, it works well! Great work @r-plus!

**Comment by r-plus** [comment]
Test result will be changed by Xcode preference.

`dw` failed two cases I pasted are passed when I disable the Xcode preference `Including white-space only lines`
<img width="942" alt="スクリーンショット 2021-01-16 13 34 23" src="https://user-images.githubusercontent.com/425216/104797203-aa472b80-57ff-11eb-9da8-c392f17bc2b5.png">

After disabled it, only one failing case, same as @smolck's.
<img width="829" alt="スクリーンショット 2021-01-16 13 30 07" src="https://user-images.githubusercontent.com/425216/104797227-d4005280-57ff-11eb-9e32-2210497a79a4.png">

**Comment by r-plus** [comment]
looks like last failing test case `O<ESC>` is known broken test case commented as `FIXME: expected text`
https://github.com/XVimProject/XVim2/blob/master/XVim2/UnitTest/XVimTester%2BIssues.m#L87

initial text is `""` empty string, then type `O<ESC>`, expected `<CR>`.
Where came from `aaa bbb ccc` string...?

Actually, `Shift+o<ESC>` is correctly works well :)

**Comment by r-plus** [comment]
fixed blank text initializing for unit test and test case expected result for fitting Xcode 12.

finally, all passed.
<img width="871" alt="スクリーンショット 2021-01-16 14 26 18" src="https://user-images.githubusercontent.com/425216/104798129-74a64080-5807-11eb-9078-e0d9e57d641c.png">

**Comment by jspavlick** [comment]
> @jspavlick Is there anything other than `set debug` in you `.xvimrc`?
> 
> For me, I ran the tests on the latest from the `feature/support_arm` branch, and this was the result:
> ![Screen Shot 2021-01-15 at 11 15 02 AM](https://user-images.githubusercontent.com/46855713/104758193-ad6ce980-5723-11eb-9acd-7dc3eb0791a6.png)
> 
> Running it under Rosetta appeared to give the same thing.
> 
> Just from a quick test moving around the editor, it works well! Great work @r-plus!

after emptying my .xvimrc and switching to feature/support_arm a8a3e886d145c3f172bae80aaf4498a880aa987e I still get this. Maybe we should just ignore my sad machine and test results 😅 

<img width="812" alt="image" src="https://user-images.githubusercontent.com/5431318/104798467-2ded2200-57d8-11eb-8781-1c8488065add.png">

**Comment by r-plus** [comment]
@jspavlick This unit test expected Xcode default preference.
Looking your results, Expected and Actual differences are space width.
Are you changing indent preference?

**Comment by jspavlick** [comment]
Good thinking, @r-plus ! After changing my indentation from `2` to `4` in Xcode, everything passes!

<img width="812" alt="image" src="https://user-images.githubusercontent.com/5431318/104806622-f4bdad80-57e9-11eb-8991-47fea5964ba1.png">

**Comment by jspavlick** [comment]
I got my M1 Mac Mini (finally) and have set it up. Wow, this thing is amazing. Product > Archive is 3.7x faster than my Mid 2014 MBP, and I simply cannot get this thing to make fan noise. It's dead silent. 

I got XVim2 installed and working. All 463 tests pass. And Xvim seems to work perfectly from what I can tell. Very good job @r-plus !

I did get one crash while running the tests, but I can't replicate it. Probably not a big deal. I am also experiencing this issue: https://github.com/XVimProject/XVim2/issues/340 

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/5431318/104874061-0bd3db00-5963-11eb-9f2f-843dd9a7b800.png">

**Comment by jhirsh** [comment]
`feature/support-arm` also passes on my M1 MBA.

@r-plus, thank you for tackling this! 🦾

**Comment by jspavlick** [comment]
@r-plus when are we merging this into master? Go claim your bounty!

**Comment by r-plus** [comment]
@jspavlick I'm wondering if it's okay to self-merging pull request. (I’m new face of committer for this repo)

**Comment by pebble8888** [comment]
@r-plus 
I think you can merge your PR and close this issue.

**Comment by r-plus** [comment]
okey, thanks! I'll merge it.

**Comment by r-plus** [comment]
I just merge it to develop and master branches.
Close this issue, thanks to all supported great vimmers.
